
alias b='bun dev'
alias cleanup='sudo pacman -Rns $(pacman -Qdtq)'
alias conf='vim ~/.bashrc'
alias dcdown='docker-compose -f docker-compose.dev.yml down'
alias dcup='docker-compose -f docker-compose.dev.yml up -d'
alias drestart='dcdown -v && dcup && cd backups/'
alias ga='git add .'
alias gc='git commit'
alias gpl='git pull'
alias gps='git push'
alias grep='grep --color=auto'
alias home='ssh russssl@192.168.1.10'
alias ls='ls --color=auto'
alias p='pnpm dev'
alias pd='pnpm dev:debug'
alias src='source ~/.bashrc'
alias y='yarn dev'
alias yb='yarn build && yarn dev'
alias yf='yarn dev --force'
